val/include/bsa_acs_pcie_spec.h
This commit corrects offset of Device Capability 2 and
Device Control 2 registers.
=> Fix offsets of PCIe Capability registers

test_pool/power_wakeup/operating_system/test_os_u001.c, val/include/bsa_acs_pe.h, val/src/AArch64/PeTestSupport.S, val/sys_arch_src/smmu_v3/smmu_v3.c, val/sys_arch_src/smmu_v3/smmu_v3.h
- SMMU init code updated with timeout and memory barrier.
- Test 501 updated to treat PE wakeup from any interrupt as success
=> SMMU hang issue fix and WD test 501 updates

test_pool/pcie/operating_system/test_os_p002.c, val/include/bsa_acs_pcie.h
- If the device is valid PCIe device, checks if the config space till last capability is accessible.
- If the device is not a valid PCIe device, then access to the start and end of the config space should return all 1's.
=> PCIe: Test p002 enhancement

val/sys_arch_src/smmu_v3/smmu_v3.c
ArmExecuteMemoryBarrier functionality is needed only for UEFI targets.
=> Excluding memory barrier API from linux acs build

test_pool/pcie/operating_system/test_os_p061.c, val/include/val_interface.h, val/src/acs_pcie.c
- Modified to use pcie table instead peripheral table to get
the PCIe device BDF.
Authored-by: Gowtham Siddarth <gowtham.siddarth@arm.com>
=> PCIe: Enhancement of unaligned access

test_pool/peripherals/operating_system/test_os_d003.c
* UART status register bits can change based on UART activity irrespective of test write check which can lead to false failures
* Currently test is making sure that no exception during write to RO
registers
Signed-off-by: jisjos01 <jiss.jose@arm.com>
=> Removed read only check for UART status registers

platform/pal_uefi_acpi/src/pal_timer_wd.c
Some system are using rev 1 of GTDT table. GTDT table parsing code updated to handle different GTDT revisions.
=> Handling different version of GTDT table

uefi_app/BsaAcsMain.c
- moved val_print call before log file handle is closed.
Signed off by: Amrathesh <amrathesh@arm.com>
=> moving val_print before log file close

test_pool/smmu/hypervisor/test_hyp_i002.c, test_pool/smmu/operating_system/test_os_i003.c, test_pool/smmu/operating_system/test_os_i004.c, test_pool/smmu/operating_system/test_os_i005.c, test_pool/smmu/operating_system/test_os_i006.c, val/src/acs_pe.c, val/src/acs_smmu.c, val/src/acs_status.c
Implementation of SRSv1.3 exclusion list.
Below is the list of tests excluded from the BSA binary and the rules which test used to cover.
* 15 - B_PE_17
* 16 - B_SEC_01
* 17 - B_SEC_02
* 18 - B_SEC_03
* 19 - B_SEC_04
* 20 - B_SEC_05
* 309 - B_SMMU_11, B_SMMU_22
* 307 - B_SMMU_13
* 308 - B_SMMU_14
* 303 - B_SMMU_03  (305 test is now renamed to 303)
* 304 - B_SMMU_04, B_SMMU_05 (306 test is now renamed to 304)
* 352 - B_SMMU_20 (352 now checks only B_SMMU_18)
* 354 - B_SMMU_21
* 355 - B_SMMU_23
=> SRSv1.3 Exclusion List

test_pool/power_wakeup/operating_system/test_os_u001.c
Test `501 : Wake from Watchdog WS0 Int` fails dues to interrupt type (edge vs level) not being set as specified in the GTDT table.  The code is present in test `701  : Non Secure Watchdog Access`, which passes.
This patch ports the code to set the interrupt type from 701 to 501.  Test 501 passes with the fix.
=> Port code to set interrupt level from test_os_w002.c

test_pool/pcie/operating_system/test_os_p020.c, test_pool/pcie/operating_system/test_os_p021.c, test_pool/pcie/operating_system/test_os_p022.c, test_pool/pcie/operating_system/test_os_p024.c, test_pool/pcie/operating_system/test_os_p025.c, test_pool/pcie/operating_system/test_os_p026.c, test_pool/pcie/operating_system/test_os_p028.c, test_pool/pcie/operating_system/test_os_p030.c, test_pool/pcie/operating_system/test_os_p031.c, test_pool/pcie/operating_system/test_os_p032.c, test_pool/pcie/operating_system/test_os_p033.c, test_pool/pcie/operating_system/test_os_p035.c, test_pool/pcie/operating_system/test_os_p061.c, val/src/acs_pcie.c
Fix for #40
* rciep and iep will not be part of bdf table
* rciep and iep only pcie test omitted from BSA
* pcie test 5, 10, 12, 13, 14, 15, 16, 23, 27, 29, 34
* pcie register test TEST_DESC changed to omit rciep and iep rule id
=> RCiEP and iEP device rules are for SBSA L6

test_pool/peripherals/operating_system/test_os_d001.c
As per BSA peripheral rules B_PER_01, 02, and 04, USB ctrl which is not compliant to EHCI or XHCI interface is allowed if not used to boot and install an OS.
It is unfeasible to determine if a USB is used for OS installation or boot from the test, so as a workaround test will explicitly print r details (bdf, interface type) of USB controller which is not EHCI/XHCI complaint. Using the prints and manual check it can be determined if the test failure can be waived.
=>  bsa #42 test updated to print USB dev bdf and interface

test_pool/Makefile, test_pool/pcie/operating_system/test_os_p067.c, test_pool/pcie/operating_system/test_os_p068.c, val/include/bsa_acs_pcie.h, val/include/val_interface.h, val/src/acs_pcie.c, val/src/acs_smmu.c
SBSA linux test 407 and 408 targetting BSA rules PCI_MSI_01 and PCI_MSI_02 are ported to BSA as pcie linux test 863 and 867
=> Ported SBSA pcie linux test 407, 408 to BSA

test_pool/pcie/operating_system/test_os_p009.c
According to "PCI Code and ID Assignment Specification Revision 1.11" values up to 0x2C are allowed.
Fix for https://github.com/ARM-software/bsa-acs/issues/56
Signed-off-by: Gowtham Siddarth <gowtham.siddarth@arm.com>
Change-Id: I670e41e2670bcfae828038d8aa37c0c898b48b8c
=> Increase a value of PCIE_ECAP_ID_END macro

platform/pal_uefi_acpi/include/pal_uefi.h, platform/pal_uefi_acpi/src/pal_pcie.c, platform/pal_uefi_dt/include/pal_uefi.h, platform/pal_uefi_dt/src/pal_pcie.c, test_pool/exerciser/operating_system/test_os_e015.c, test_pool/pcie/operating_system/test_os_p005.c, test_pool/pcie/operating_system/test_os_p033.c, test_pool/pcie/operating_system/test_os_p035.c, test_pool/pcie/operating_system/test_os_p036.c, uefi_app/BsaAcs.inf, val/include/bsa_acs_pcie.h, val/include/bsa_acs_pcie_spec.h, val/include/pal_interface.h, val/include/val_interface.h, val/src/acs_pcie.c
- Enhancement of 804
- Getting user-defined offset
- Addition of 805 for checking Prefetchable memory range
- Return error when capability not present
=> PCIe: PCIe updates and enhancements

platform/pal_uefi_dt/src/pal_pe.c
Previous 'i' is used in various place make the forever loop.
Signed-off-by: Huynh Thanh Hung <hunght.vn8@gmail.com>
=> pal_uefi_dt: pal_pe: Correct idx variable when parsing fdt

test_pool/pcie/operating_system/test_os_p037.c
PCIe test 837 to be run for all valid BDFs eventhough if any of the BDF check fails.
Signed-off-by: Gowtham Siddarth <gowtham.siddarth@arm.com>
=> PCIe: Continue to test other BDFs on failure

test_pool/pcie/operating_system/test_os_p039.c
PCIe test 39 checks if the device has MSI/MSI-X capability, but in case the device doesn't support interrupt generation then the test fails. Check added to skip device in case device doesn't support interrupt generation.
=> PCIe test-39 updated to check if pcie device support interrupt generation

test_pool/pe/operating_system/test_os_c004.c
Issue #86 : Bug fix for 4KB granule support
- updated PE test to support 4KB granule with LPA2 by checking the correct values from TGran4 bits [31:28] in ID_AA64MMFR0_EL1
Signed-off-by: Balaji Gontumukkala <balaji.gontumukkala@arm.com>
=> Issue #86 : Bug fix for 4KB granule support

val/src/acs_iovirt.c, val/src/acs_pcie.c
Fix for #91 
SMMU INFO, PCIE INFO prints are updated from hexadecimal format to decimal format.
Signed-off-by: Balaji Gontumukkala <balaji.gontumukkala@arm.com>
=> SMMU INFO, PCIE INFO prints are updated from hexadecimal format to decimal format

platform/pal_uefi_acpi/src/pal_timer_wd.c, test_pool/gic/hypervisor/test_hyp_g002.c, test_pool/gic/hypervisor/test_hyp_g003.c, uefi_app/BsaAcs.inf, val/include/bsa_acs_gic.h, val/src/acs_gic.c
Fix  #94 
- updated the GIC hypervisor test B_PPI_02 into three individual tests to check NS EL2-Virt, NS EL2-Phy and GIC Maintenance interrupts
- Minor formatting changes
Signed-off-by: Balaji Gontumukkala <balaji.gontumukkala@arm.com>
=> GIC test 226 divided into three separate tests

val/include/val_interface.h, val/src/acs_exerciser.c, val/src/acs_gic.c, val/src/acs_memory.c, val/src/acs_pcie.c, val/src/acs_pe.c, val/src/acs_peripherals.c, val/src/acs_smmu.c, val/src/acs_test_infra.c, val/src/acs_timer.c, val/src/acs_wakeup.c, val/src/acs_wd.c
#93 
- added val_print_test_end function in acs_test_infra.c
- removed the conditions to check the status of tests and added val_print_test_end function to check tests status
=> Unify test result info like in sbsa

platform/pal_uefi_acpi/include/pal_uefi.h, platform/pal_uefi_acpi/src/pal_gic.c, platform/pal_uefi_dt/include/pal_uefi.h, platform/pal_uefi_dt/src/pal_dt_debug.c, platform/pal_uefi_dt/src/pal_gic.c, test_pool/gic/operating_system/test_os_g005.c, val/include/bsa_acs_gic.h, val/include/pal_interface.h, val/src/acs_gic.c, val/sys_arch_src/gic/v3/gic_v3.c
Bug fix for #102 
Test is currently using GIC RD base address for the SGI bits and
not derving RD base per PE. For systems in which GIC RD base is not mapped
to any valid PE cores, test is failing incorrectly
Changes
- GIC_INFO_HDR num_gicrd split into num_gicc_rd and num_gicr_rd
- pal and val files changes to accomodate num_gicc_rd and num_gicr_rd
- Change in val_get_gicr_base to take care of systems which have multiple GICR RD structure
- function prototype changes for build success
=> Test 205 updated to derive correct GIC RD base as per PE MPIDR

test_pool/watchdog/operating_system/test_os_w001.c, test_pool/watchdog/operating_system/test_os_w002.c
- Changed BSA watchdog test 701 & 702 to fail if no non-secure watchdog timer is found for BSA run for SBSA.
-  Minor Formatting changes
=> For SBSA complaince, NS watchdog is mandatory

test_pool/power_wakeup/operating_system/test_os_u001.c
Fixes #106
- fixed order of power and wakeup tests to be in numeric order.
- test 501 - 503 are PE timer tests, 504 for Watchdog and 505 for system counter.
=> Fix order of Power and Wakeup tests

platform/pal_uefi_acpi/include/pal_uefi.h, platform/pal_uefi_acpi/src/AArch64/ArmSmc.S, platform/pal_uefi_acpi/src/pal_acpi.c, platform/pal_uefi_acpi/src/pal_pe.c, platform/pal_uefi_dt/include/pal_dt_spec.h, platform/pal_uefi_dt/include/pal_uefi.h, platform/pal_uefi_dt/src/AArch64/ArmSmc.S, platform/pal_uefi_dt/src/pal_dt.c, platform/pal_uefi_dt/src/pal_dt_debug.c, platform/pal_uefi_dt/src/pal_gic.c, platform/pal_uefi_dt/src/pal_misc.c, platform/pal_uefi_dt/src/pal_pe.c, val/include/pal_interface.h, val/src/acs_pe_infra.c, val/src/acs_wakeup.c
PSCI service call conduit changes
- PSCI can use either HVC or SMC as the conduit method, for ACPI based systems FADT acpi table will give the method to be used.
- For DT based systems, psci node will convey the information
Use F/W interrupt handlers for edk2 + DT systems.
- Some systems like RPI4 support both ACPI and DT on top of edk2. For such systems when using in edk2+DT mode, the interrupt handlers API will be supported by F/W.  In such cases no need to use ACS interrupt handlers.
- But for systems working in u-boot+DT mode, ACS interrupt handlers are needed.
=>  PSCI service call conduit changes + Use F/W interrupt handlers for edk2 + DT systems

test_pool/gic/operating_system/test_os_its004.c
Debug prints for test 279
- Test 279 consists of 2 parts, Part 1 checks for StreamID-DeviceID in case when SMMU is present. 
- Part 2 checks for ReqID-DeviceID in all the cases. Added Print message in case any of the parts is skipping
=> Issue #90 - Debug prints for test 279

val/src/acs_iovirt.c
Fix for #117  
- Added print statement in val_iovirt_create_info_table to print SMMU minor version in case of smmu v3.
=> Print SMMU minor version in INFO prints

platform/pal_uefi_acpi/src/pal_gic.c, val/src/acs_gic.c
Issue #138 : Ignore GICR Base Address in GICC when GICR Present
- Added the code to ignore GICR base address present in GICC structure in case when GICR structure is present in ACPI Table.
=> Fix for Issue #138

test_pool/exerciser/operating_system/test_os_e001.c, test_pool/exerciser/operating_system/test_os_e002.c, test_pool/exerciser/operating_system/test_os_e004.c, test_pool/exerciser/operating_system/test_os_e007.c, test_pool/exerciser/operating_system/test_os_e008.c, test_pool/exerciser/operating_system/test_os_e009.c, test_pool/exerciser/operating_system/test_os_e010.c, test_pool/exerciser/operating_system/test_os_e011.c, test_pool/exerciser/operating_system/test_os_e012.c, test_pool/exerciser/operating_system/test_os_e013.c, test_pool/exerciser/operating_system/test_os_e014.c, test_pool/exerciser/operating_system/test_os_e015.c, test_pool/gic/hypervisor/test_hyp_g001.c, test_pool/gic/operating_system/test_os_v2m003.c, test_pool/gic/operating_system/test_os_v2m004.c, test_pool/memory_map/operating_system/test_os_m002.c, test_pool/pcie/operating_system/test_os_p002.c, test_pool/pcie/operating_system/test_os_p004.c, test_pool/pcie/operating_system/test_os_p005.c, test_pool/pcie/operating_system/test_os_p008.c, test_pool/pcie/operating_system/test_os_p035.c, test_pool/pe/operating_system/test_os_c013.c, test_pool/peripherals/operating_system/test_os_d004.c, test_pool/smmu/operating_system/test_os_i002.c, test_pool/timer/operating_system/test_os_t003.c
- "must" carries a stronger sense of obligation or necessity than "should" hence using it for prints conveying non-compilance to mandatory rules.
=> use of verb "must" in place "should" to express requirements

test_pool/gic/hypervisor/test_hyp_g001.c, test_pool/gic/hypervisor/test_hyp_g002.c, test_pool/gic/operating_system/test_os_g006.c, test_pool/pcie/operating_system/test_os_p009.c, test_pool/timer/operating_system/test_os_t004.c, test_pool/timer/operating_system/test_os_t005.c
Fix for #133
* Moved system timer and failsafe timer timeout to system counter base
* debug changes to print which timer interrupt is received
* backmerge of pcie bug fix
* added el0 phy timer (failsafe) handler in test
=> Test 205 system timer timeout moved to sys counter base

linux_app/bsa-acs-app/bsa_drv_intf.c
- Added condition to check error for call_drv_wait_for_completion function return value
=> During error Linux driver doesn't exit

val/include/bsa_acs_pcie_spec.h, val/src/acs_pcie.c
- Fix for #150 
- Added changes to print additional information on the number of Upstream ports of a switch, Downstream ports of a switch, PCIe to PCI/PCI-X Bridge and PCIe to PCI/PCI-X to PCIe Bridge to match the total BDF's identified
=> Added additional prints to print info of all cards in PCI info block

platform/pal_baremetal/src/pal_pcie.c, platform/pal_uefi_acpi/BsaPalLib.inf, platform/pal_uefi_acpi/src/pal_pcie.c, platform/pal_uefi_dt/BsaPalLib.inf, platform/pal_uefi_dt/src/pal_pcie.c, test_pool/pcie/operating_system/test_os_p004.c, test_pool/pcie/operating_system/test_os_p005.c, val/include/bsa_acs_pcie.h, val/include/pal_interface.h, val/src/acs_pcie.c
- A fixed offset translation scheme is implemented to establish a connection between the physical address space of the PE and the PCI memory. This scheme enables the mirroring of a PE physical address space window above 4GB into the PCI memory space below 4GB. To achieve this, the PHB must support the translation method (_TRA) to convert the address from the PE's perspective, particularly when the MMIO32 BAR exceeds 4GB. In UEFI, the EFI_PCI_IO_PROTOCOL handles this translation, which is utilized by the modified ACS to incorporate the PCIIO protocol and leverage UEFI's offset translation mechanism.
- Fixes https://github.com/ARM-software/bsa-acs/issues/26
=>  Allow ACS to support fixed offset translation scheme

val/src/acs_pcie.c
- The PCIe table is populated with only RP's and EP's. But the RP's have information of all devices spawned under it.
- Hence adding enabling of BME and MSE enable for all valid PCIe devices.
=> Enabled BME and MSE for all PCIe devices

val/src/acs_pe_infra.c
Issue ARM-software/sbsa-acs#348 : Added cache-invalidate operation
- Secondary cores directly read g_pe_info_table->pe_info ->mpidr/pe_num without cache-invalidate operation in val_pe_get_index_mpid().
=> Added cache-invalidate operation

baremetal_app/BsaAcs.inf, test_pool/exerciser/operating_system/test_os_e014.c, test_pool/exerciser/operating_system/test_os_e016.c, test_pool/exerciser/operating_system/test_os_e017.c, test_pool/exerciser/operating_system/test_os_e018.c, uefi_app/BsaAcs.inf, val/include/bsa_acs_exerciser.h, val/src/acs_exerciser.c
- Exerciser table is created with all PCIe devices, following exerciser tests can be moved to BSA and removed from SBSA.
- SBSA e002: move to BSA test_os_e016 
- SBSA e004: move to BSA test_os_e017 
- SBSA e005: move to BSA test_os_e018
=> Moving relevant tests from SBSA to BSA

baremetal_app/BsaAcsMain.c, uefi_app/BsaAcsMain.c, val/include/val_interface.h, val/src/acs_exerciser.c, val/src/acs_gic.c, val/src/acs_memory.c, val/src/acs_pcie.c, val/src/acs_pe.c, val/src/acs_peripherals.c, val/src/acs_smmu.c, val/src/acs_test_infra.c, val/src/acs_timer.c, val/src/acs_wakeup.c, val/src/acs_wd.c
- Added a VAL API that prints out module header.
- Printing module header only if any test in the module is to be executed. Else skipping module headers as well.
=> Added API to print module header

baremetal_app/BsaAcsMain.c, platform/pal_baremetal/FVP/RDN2/include/platform_override_fvp.h, platform/pal_baremetal/FVP/RDN2/src/platform_cfg_fvp.c, uefi_app/BsaAcsMain.c, val/include/bsa_acs_cfg.h, val/include/bsa_acs_common.h, val/src/acs_exerciser.c, val/src/acs_gic.c, val/src/acs_memory.c, val/src/acs_pcie.c, val/src/acs_pe.c, val/src/acs_peripherals.c, val/src/acs_smmu.c, val/src/acs_test_infra.c, val/src/acs_timer.c, val/src/acs_wakeup.c, val/src/acs_wd.c
- Added a VAL API that returns if the module should be skipped based on any tests to be run using user override options.
- Users can now give any number of parameters to -t and -m options which allows them to run any specific tests/modules without any limitations.
- Made necessary infra changes to baremetal also.
=> Removing limitation on -t -m options

baremetal_app/BsaAcsMain.c, test_pool/power_wakeup/operating_system/test_os_u001.c, uefi_app/BsaAcsMain.c, val/include/bsa_acs_cfg.h, val/src/acs_gic.c, val/src/acs_timer.c
In some platforms when running bsa at EL1, an exception is observed when EL1 timers are accessed.  el1physkip added as debug option to skip the timer access 
- implemented "-el1physkip" command line option to skip EL1 register checks
- commented el1 timer register read and write api's which causing execption in val_timer_create_info_table function
=> EL1 timer skip debug option added

test_pool/pcie/operating_system/test_os_p003.c, val/include/bsa_acs_pcie.h
- Added additional return type when EP has no RP and included prints that reflect the same in PCIe test 803.
=> Improving prints when EP without RP is encountered

val/src/acs_pcie.c
- BME and MSE bits enablement changes were added to include RP which has a legacy device connected to them for compliance check. On Linux, USB disconnect issue was seen on a system that has USB connected via a PCIe controller. It could be due to difference between the number of valid BDF's found by ACS vs devices listed by linux (lspci) Enabling of BME and MSE bits of a PCIe device (which is found by ACS but not listed by lspci) could have triggered the USB disconnect issue.
- BME and MSE bits enablement is required by tests that performs BAR related checks. In Linux ACS there are no such tests present, so enabling these bits can be skipped for linux enviroment. Enabling BME and MSE bits only for UEFI
=> Enabling BME and MSE bits only for UEFI

platform/pal_baremetal/src/pal_peripherals.c, test_pool/memory_map/operating_system/test_os_m004.c, val/src/acs_memory.c
- Added a guard as test should proceed only if peripheral is connected as PCIe device, else the device id will be Invalid
=> Test 104: Fix to run test only if Peripheral is connected as PCIe device

val/include/bsa_acs_exerciser.h, val/include/val_interface.h, val/src/acs_gic.c
- Mismatch between function prototype and definition causing build failure with GCC 13.1.1
- Fixed the function prototype for val_get_exerciser_err_info, val_wd_get_info and val_gic_get_info
- Resolves: #174
=> Fix for mismatch in function prototypes

test_pool/pcie/operating_system/test_os_p035.c
- The BAR values need not be all 0's after FLR is completed. It can be any value.
=> Fix for issue #192: BAR Values should not be 0 after FLR

test_pool/pcie/operating_system/test_os_p035.c
- Few devices might require more than 100ms to complete the FLR.
- Hence modified to below logic Check if FLR PCIe capability is set If so, initiate FLR and Wait 100 ms Read back the VID register from config space If value is 0xFF, delay for 1 ms, then read again Keep polling until a maximum timeout of 5 secs
=> fix for issue #194 : FLR test should poll for device readiness

val/src/acs_exerciser.c, val/src/acs_gic.c, val/src/acs_memory.c, val/src/acs_pcie.c, val/src/acs_pe.c, val/src/acs_peripherals.c, val/src/acs_smmu.c, val/src/acs_status.c, val/src/acs_test_infra.c, val/src/acs_timer.c, val/src/acs_wakeup.c, val/src/acs_wd.c
- No console prints for tests not mentioned in -t option.
- Total test count aligns with the tests that are actually being run with user override options.
=> Enhancements to -t option

.github/workflows/build-bsa-uefi.yml, README.md, patches/edk2-202208-bsa-acpi.diff, patches/edk2-202208-bsa-dt.diff
- added actions YAML and required edk2 patches
- added build-status badge for scheduled cron.
- the workflow as two jobs for acpi and dt targets.
=> Enable BSA UEFI build Github actions

test_pool/pcie/operating_system/test_os_p035.c
- Skip the FLR check for mass storage devices as they will be reset and logs cannot be stored
=> FLR should not be run for Mass storage devices

test_pool/peripherals/operating_system/test_os_d005.c
-The defined type of uart_base is changed to uint64_t -The UART_BASE print modifier is changed from 'X' to "llX'
Fixes: https://github.com/ARM-software/arm-systemready/issues/105
=> UART_BASE Type is changed to uint64_t.

test_pool/pe/hypervisor/test_hyp_c004.c, test_pool/pe/operating_system/test_os_c009.c, test_pool/pe/operating_system/test_os_c011.c, test_pool/pe/operating_system/test_os_c012.c, val/include/val_interface.h, val/src/acs_pe_infra.c
Fixes:#199
- Added prints which outputs data reported by the system and what is expected for primary PE.
=> PE tests 9, 11, 12, and 54 are made more verbose on failure

uefi_app/BsaAcsMain.c
- Resolves: #210
- Removed -rciep and -iep options in UEFI help message which are not being used anymore.
=> Removed unused command line options from UEFI help.

val/src/acs_pcie.c
- Better messaging by adding prints of the capability id that is not found for register check tests
=> Better messaging of capability check tests

README.md, platform/pal_uefi_acpi/src/pal_peripherals.c
For systems that present firmware compliant to SBBR, BSA depends on SPCR acpi table to get UART information.
UEFI console setting must be set to "serial" on these systems
=> Added prints to inform SPCR table not found

uefi_app/BsaAcs.h
Fix for #226 
Expanding the IORT table size to support 2400 nodes
=> Expanding the size of the IORT info table

platform/pal_uefi_acpi/src/pal_pe.c
Adjusted Stack to provide aarch64 required 16-byte alignment
- ACS PE tests do not execute properly on aarch64 systems due to secondary stack misalignment. The arm handbook mentions that aarch64 requires a 16 byte alignment.
This PR includes modifications that allow for aarch64 compatible alignment as well as storing the original pointer given to us by AllocatePool so we can still free the memory if the need ever comes up.
=> Issue #239 : Adjusted PalAllocateSecondaryStack Alignment

test_pool/memory_map/operating_system/test_os_m002.c, test_pool/pe/operating_system/test_os_c001.c
Fixes for #249 - 
PE test 1: Check for PMuv3 support before reading PMU registers.
Mem test 102: Added debug print for memory address
=> Check PMUv3 support before reading PMU registers

platform/pal_baremetal/common/include/pal_common_support.h, platform/pal_uefi_acpi/include/pal_uefi.h, platform/pal_uefi_dt/include/pal_uefi.h, test_pool/pcie/operating_system/test_os_p064.c, val/include/pal_interface.h
Fixes irq_to_hwirq() API should have a return type of uint64
=> Fixes irq_to_hwirq() API should have a return type of uint64

val/src/acs_pcie.c
Fixes #256
Added debug prints to log message when BDF is skipped due to
* PCI Express capability not present
* BDF is host bridge
* Platform input as marked BDF as invalid.
=> Added Debug message to print BDF skip reason

val/src/acs_pcie.c
Fixes #255
For PCIe bitfield values and attributes tests, logs captures value of offset where the BITS under test are present.
Debug print is now modified to only prints value of BITS under test
=> Dump only the value of BITS which are under test

.github/workflows/build-bsa-uefi.yml
Errata updates to Test requires new register read, which are supported by toolchain > 10.2
=> Upgrade Github Action toolchain to 13.2 version

test_pool/pe/operating_system/test_os_c014.c, val/include/bsa_acs_pe.h, val/src/AArch64/PeRegSysSupport.S, val/src/acs_pe.c
BSA Errata Mantis - 590 & 596
-The B_PE_15 is changed to check for both generic and address auth 
-The rule is changed to check both QARMA5 and QARMA3 algorithm 
-The implementation defined algorithm is not recommended
=> BSA Errata Mantis - 590 & 596

test_pool/exerciser/operating_system/test_os_e001.c, test_pool/exerciser/operating_system/test_os_e002.c, val/include/bsa_acs_pcie_spec.h, val/include/val_interface.h, val/src/acs_pcie.c
- Introduced APIs to read, store default ACS control register bits and to write them back at the end of the test.
- Changes made to exerciser tests e001 and e002 to restore default ACS control reg values.
=> Restoring default values of ACS Ctrl register

val/sbsa/include/sbsa_acs_ete.h, val/sbsa/src/sbsa_acs_ete.c, val/sbsa/src/sbsa_execute_test.c
Linux also exposes trace buffer related register with same macro name as used in ACS code which is resulting in redefine error build failure.
Appending ACS_ in trace buffer registers macro.
=> Changes for sbsa linux build

pal/baremetal/target/RDN2/sbsa/src/platform_cfg_fvp.c, val/common/include/acs_cfg.h, val/sbsa/src/sbsa_execute_test.c
- Added new argument "-only" to only run tests belonging to a specific level of compliance in SBSA
- Changes in VAL files to check level parameter when only option is passed
- Added new variable in PAL
=> Changes for new argument "-only"

val/SbsaValLib.inf, val/SbsaValNistLib.inf
- -I compiler option not required in SbsaValLib.inf and SbsaValNistLib.inf files. Removed redundant code.
=> Removing unwanted compiler flags from .inf files

test_pool/pcie/operating_system/test_os_p035.c
- Skipped the FLR check for ethernet devices as FLR might cause data corruption and disrupt the init of the device
=> Skipping Ethernet device for FLR test

pal/uefi_dt/bsa/include/pal_uefi.h, pal/uefi_dt/bsa/src/pal_iovirt.c
- DT pal layer PE and SMMU info table struct were missing some VAL info table members.
=> Alinging dt pal and val pe and smmu info table struct

pal/baremetal/target/RDN2/sbsa/src/platform_cfg_fvp.c
- g_sbsa_only_level should be set to 0 to run all the levels by default.
- If g_sbsa_only_level is set to any level between 3 to 7, only the tests associated to that level run.
=> Bug fix for SBSA -only option in Baremetal

test_pool/smmu/operating_system/test_os_i003.c, val/common/include/acs_memory.h, val/common/src/acs_memory.c, val/common/src/acs_mmu.c
Fixes #162
B_SMMU_06 rule is updated to also account for system physical address
space.If SPAS is 52-bit, then PE and SMMU should also support it.
There is no architecture method to know if SPAS is 52 bit or not, test
is **only** checking uefi memory map to know if any address is 52 bit.
Test updated to
* PASS : if both PE and SMMU supports 52 bit
* FAIL : if PE or SMMU not support 52 bit, but uefi mem map has some 52 bit addr mem region
Other cases will be treated as SKIP, and require manual check to verify if system SPAS is 52 bit or not.
=> SMMU test 3 updates for mantis #624

test_pool/pe/operating_system/test_os_c001.c
The PE test - 01 has been updated to check for all fails in registers and cache.
The secondary PE registers value can be stored in a structure and can be printed by Primary Pe for both fail and info cases.
Fixes #303, #304, #310
=> Secondary PE Print for pe test 01

test_pool/pe/operating_system/test_os_c001.c
BSA specification doesn't have permitted difference for PMCR_EL0 register, updating the test to sync with specification
Fixes #319
=> Remove mask used by test for PMCR_EL0 register

test_pool/exerciser/operating_system/test_os_e005.c
- If the system doesn't support PASID Extended Cap, don't fail the test.
=> Remove PASID ECap fail check in e005

test_pool/peripherals/operating_system/test_os_d003.c, test_pool/timer/operating_system/test_os_t004.c, test_pool/watchdog/operating_system/test_os_w002.c, val/common/sys_arch_src/gic/v3/gic_v3.c, val/common/sys_arch_src/gic/v3/gic_v3.h
-The tests now has check for Spi and Espi interrupt 
-The test will fail if the interrupt is LPI or PPI
=> Errata Mantis-656: Remove LPI as a valid option

test_pool/pe/operating_system/test_os_c001.c, val/common/src/AArch64/PeRegSysSupport.S
- Enabling ID_MMFR4_El1, PMSIDR_EL1, ERRIDR_EL1, LORID_EL1, ID_AA64MMFR2_EL1
- Removing ERR<n>FR_EL1 which depends on MMIO access
Change-Id: Ifc40d6fe9377b8c3e476f1e562523c5f487c91ff
=> PE 01 Enabling last few registers

pal/baremetal/sbsa/include/pal_sbsa_common_support.h, pal/baremetal/sbsa/src/pal_sbsa_mpam.c, pal/baremetal/sbsa/src/pal_sbsa_pcc.c, pal/baremetal/target/RDN2/sbsa/include/platform_override_sbsa_fvp.h, pal/baremetal/target/RDN2/sbsa/include/platform_override_sbsa_struct.h, pal/baremetal/target/RDN2/sbsa/src/platform_cfg_fvp.c, pal/uefi_acpi/SbsaPalLib.inf, pal/uefi_acpi/SbsaPalNistLib.inf, pal/uefi_acpi/sbsa/include/pal_sbsa_uefi.h, pal/uefi_acpi/sbsa/src/pal_sbsa_mpam.c, pal/uefi_acpi/sbsa/src/pal_sbsa_pcc.c, val/SbsaValLib.inf, val/SbsaValNistLib.inf, val/sbsa/include/sbsa_acs_mpam.h, val/sbsa/include/sbsa_pal_interface.h, val/sbsa/include/sbsa_val_interface.h, val/sbsa/src/sbsa_acs_mpam.c, val/sbsa/src/sbsa_acs_pcc.c
- parsing PCCT structure on demand basis.
- implemented doorbell protocol to do PCC
transactions.
- MPAM mem-map register API modified to support
both MMIO and PCC MSC interfaces.
- added PAL APIs to parse platform override values.
- Added PCC config definitions and structures.
Fixes: https://github.com/ARM-software/sbsa-acs/issues/454
=> Add support for PCCT based MPAM MSC

test_pool/pe/operating_system/test_os_c001.c, val/common/src/acs_pe_infra.c
- Only different MIDR_EL1 values will be printed in default level
- All core values of MIDR_EL1 will be printed only at verbose mode
Fixes #340
=> Test 01 over verbose

val/common/src/acs_timer.c
Fix for #343 
- Modified the timer frequency display logic.
- The frequency is displayed in a more readable format (MHz/kHz).
=> Timer frequency info log format change

mem_test/README.md, pal/uefi_acpi/common/include/pal_uefi.h, pal/uefi_acpi/common/src/pal_pe.c, pal/uefi_dt/bsa/include/pal_uefi.h, pal/uefi_dt/bsa/src/pal_pe.c, uefi_app/BsaAcsMain.c, val/common/include/pal_interface.h, val/common/src/acs_pe_infra.c
When running BSA as part of systemready images, the logs are dumped in a text file.
In case bsa binary compiled for one platform (DT or ACPI) is run on another platform, the BSA binary will not find desired platform tables and exit.
In those cases, the log file pointer was not getting free.  Added code to free the pointer
=> free file pointer if BSA run on incorrect platform

pal/uefi_dt/bsa/src/pal_timer_wd.c
- Added logic to compare the baseaddress with offset, because timer frame node reg value may have baseaddress or offset.
=> Fix in Timer parsing for DT Platform

mem_test/README.md, pal/uefi_acpi/common/include/pal_uefi.h, pal/uefi_acpi/common/src/pal_pe.c, pal/uefi_dt/bsa/include/pal_uefi.h, pal/uefi_dt/bsa/src/pal_pe.c, uefi_app/BsaAcsMain.c, val/common/include/pal_interface.h, val/common/src/acs_pe_infra.c
When running BSA app compiled for ACPI on DT or (compiled for DT and running on ACPI), due to desired platform tables not found app will exit.
In such cases, the file pointer was not getting free...add code to free the pointer
=> free file pointer if BSA app exit due to no PE or GIC found.

val/sbsa/include/sbsa_acs_pe.h, val/sbsa/src/sbsa_execute_test.c
The rule and test case for S_L7PE_03 is removed. 
It is duplicate of S_L5PE_04 in level 5.
The function c030_entry is removed.
The test case for S_L7PE_08, S_L7PE_09 will not compile.
The above rule is also removed from checklist, but the test file is there.
The function c035_entry, c036_entry is removed.
=> Errata 743 and 663

test_pool/exerciser/operating_system/test_os_e001.c, test_pool/exerciser/operating_system/test_os_e002.c, test_pool/pcie/operating_system/test_os_p017.c, test_pool/pcie/operating_system/test_os_p018.c, test_pool/pcie/operating_system/test_os_p019.c, test_pool/pcie/operating_system/test_os_p043.c
- val_pcie_p2p_support API either return non_implemented or 0. having it twice is redundant, hence removed it in tests
- In addition to the devices, the PCIe hierarchy also need to support P2P. hence added P2P check for PCIe hierarchy as well
Fixes #352
=> Fix for issue #352

val/sbsa/include/sbsa_acs_pmu.h, val/sbsa/src/sbsa_execute_test.c
The PMU_SYS_5 will not be present in default run
=> Errata 607: Rule PMU_SYS_5 is moved to recommended

test_pool/pcie/operating_system/test_os_p064.c, val/common/include/acs_pcie_spec.h
Fixes #351 
- This rule to be verified for all devices and not only the Peripheral devices.
- Skipping the Ethernet devices and the devices with the class code greater than 13h as they are reserved.
=> Fixes #351:  Check MSI(X) vectors uniqueness

baremetal_app/BsaAcsMain.c, val/bsa/src/bsa_acs_dma.c
Fixes #337 
- Call to DMA create info table is needed in BM to populate the DMA table
- The details to be populated in the platform config files
=> Fixes #337:  val_dma_create_info_table in BM

val/bsa/src/bsa_acs_gic.c, val/common/src/acs_gic.c, val/common/src/acs_gic_support.c, val/common/src/acs_pe_infra.c, val/common/sys_arch_src/gic/acs_exception.c, val/common/sys_arch_src/gic/acs_exception.h, val/common/sys_arch_src/gic/gic.c, val/common/sys_arch_src/gic/gic.h, val/common/sys_arch_src/gic/v3/gic_v3.c, val/common/sys_arch_src/gic/v3/gic_v3_extended.c
- Renaming of the VAL API's used by SBSA and BSA starting as val_bsa_* to val_module_*
=> Renaming of the VAL API's

pal/baremetal/target/RDN2/sbsa/src/pal_sbsa_bm_pcie.c, val/sbsa/include/sbsa_acs_pcie.h, val/sbsa/include/sbsa_pal_interface.h, val/sbsa/include/sbsa_val_interface.h, val/sbsa/src/sbsa_acs_pcie.c, val/sbsa/src/sbsa_execute_test.c
- Use _DSM Method to obtain the STE values from table
=> S_PCIe_11: Steering Tag properties

val/common/include/acs_pcie_spec.h, val/sbsa/include/sbsa_acs_pcie.h, val/sbsa/src/sbsa_execute_test.c
- For both iEP RP and iEP EP, checks the capability registers required for Supported speed Link Declaration
=> Implementation for IE_REG_6 to IE_REG_9

test_pool/pcie/operating_system/test_os_p064.c, val/sbsa/src/sbsa_execute_test.c
- Both MSI and MSI-X capability to be checked for the PCIe devices
- The PCIe test status to be cumulative of all result. Currently the status of previous tests are overridden by the p001 test
=> Bug fix to PCIe test 64

val/sbsa/src/sbsa_execute_test.c
- The test 867 to be run only at L6 and above.
- Removed it from running at default level to L6 and above
Fixes #389
=> Fixes #389: iEP tests to be run at L6 and above.

val/sbsa/src/sbsa_execute_test.c
related to #513
-The no smmu check before running the smmu tests is removed.
-If the smmu compatibility fails then other tests will not run
=> Smmu Test will fail for no smmu compatibility

val/sbsa/src/sbsa_execute_test.c
Fixes https://github.com/ARM-software/sbsa-acs/issues/512
- PCIe tests to not run if no ECAM
- For UEFI PCIe tests 840 and 601 , presence of ECAM is mandatory for this rule from compliance perspective
=> Fixes https://github.com/ARM-software/sbsa-acs/issues/512

pal/baremetal/common/include/pal_common_support.h, pal/baremetal/common/src/pal_pcie_enumeration.c, pal/baremetal/target/RDN2/common/src/pal_bm_exerciser.c, pal/baremetal/target/RDN2/sbsa/src/pal_sbsa_bm_exerciser.c
- Index to be incremented after the ECAM index
- When there is only one 64-bit BAR, the BAR range to be populated in the RP Register
- Fix for incrementing the 64-bit bar size, if RP supports 64-bit BAR.
- Addition of RAS and Poison feature support in the reference code for BareMetal.
=> Fix for PCIe Enumeration

docs/arm_bsa_testcase_checklist.rst, val/common/src/acs_pcie.c
Test 863 skips without explanation
- Added the skip reason for bitfield checks in VAL
Signed-off-by: Sujana M <sujana.murali@arm.com>
=> Test 863 skips without explanation

val/sbsa/src/sbsa_execute_test.c
Fixes: ARM-software/sbsa-acs#522
- As the rules are non-conditional running the tests irrespective of pmu node count.
=> Removed skip check for PMU tests

pal/baremetal/common/include/pal_common_support.h, pal/baremetal/common/src/pal_iovirt.c, val/bsa/src/bsa_acs_iovirt.c, val/common/include/pal_interface.h, val/common/src/acs_iovirt.c, val/sbsa/src/sbsa_acs_iovirt.c
- Resolves #413
- Remove mem_align dependency for UEFI
=> Align memory access only for Baremetal

test_pool/pcie/operating_system/test_os_p042.c
- iterating the bdf info table rather than peripheral table, to target all PCIe devices to check.
- test 842 was modified.
Fixes: ARM-software/arm-systemready#243
=> Run max pasid check on all PCIe devices

test_pool/pe/operating_system/test_os_c001.c
Mask Value Print Issue
-The index which is used to mask the value is changed
Fixes #424
=> Fix for #424 Issue: PE values Wrongly Masked

val/common/src/acs_pe_infra.c, val/common/src/acs_status.c
IF PE is already is on state, but fail the test but skip the PE and continue to test with others PE.
The warning print and skip print are added for this state
Fixes #411
=> Skip test for PE Already On state

test_pool/pcie/operating_system/test_os_p035.c, val/common/include/acs_pcie_spec.h
- When an FLR is initiated, and before the FLR being completed, the device will respond with Return Retry status (RRS) if Function-specific initialization sequence is not yet completed.
- The test should check for this status as well before proceeding to configuring the registers after FLR is completed
Related to #https://github.com/ARM-software/sbsa-acs/issues/526
=> Fixes https://github.com/ARM-software/sbsa-acs/issues/526: FLR test

test_pool/peripherals/operating_system/test_os_d003.c
BSA Test 604 (Check Arm GENERIC UART Interrupt) needs a larger timeout #421
Timeout is changed from **TIMEOUT_MEDIUM to TIMEOUT_LARGE.**
Fixes #421
=> Fix for ARM GENERIC UART Interrupt Timeout - #421

pal/baremetal/common/src/pal_exerciser.c, pal/baremetal/common/src/pal_pcie.c, pal/uefi_acpi/common/src/pal_exerciser.c, pal/uefi_acpi/common/src/pal_pcie.c, pal/uefi_dt/bsa/src/pal_exerciser.c, pal/uefi_dt/bsa/src/pal_pcie.c, val/common/include/acs_pcie.h, val/common/include/pal_interface.h, val/common/src/acs_pcie.c
- The UEFI PAL implementation to get the ECAM address was getting only from the segment 0 and not w.r.t the respective segments.
- Modified the PAL to check for the Segment and bus no of the BDF
=> Fixes #521 Exerciser on multi-segments

val/common/include/acs_common.h
Fixes #435 
-The defines TEST_NAME and TEST_NAME_HELPER are removed
=> Remove not used defines in acs_common.h

drtm/test_pool/dl/test_dl001.c
- Fix unaligned memory free issue in DLME region
- Added 0x4 to dlme_region_address to make it unaligned and in test 101 part-2 error case attempted to free this unaligned memory.
- To handle this correctly in the error case, now subtracts 0x4 before freeing the memory
=> Fix for Uefi Print Lib Issue in DRTM

test_pool/gic/operating_system/test_os_g005.c
Fix false PASS in GIC BSA Test-205 by correcting GICR_ISENABLER0 bit handling
Issue: Instead of verifying the status of the lower-order SGI(0-7) lines, the implementation was actually enabling all SGI lines
Changes:
- Modified the copyright year to 2025
- Writing to the bottom 8 bits of GICR_ISENABLER0 (lower order SGI(0-7) lines with 0xFF)
- Checking the status of the lower 8 bits (0-7) by performing a bitwise AND operation with 0xFF.
With these changes, the implementation status of non-secure SGIs can be correctly verified.
Without these changes, if SGIs are not implemented in the GIC Redistributor, test still incorrectly reports them as implemented
Signed-off-by: kiranrnad [kirankumarayya.ronad@arm.com](mailto:kirankumarayya.ronad@arm.com)
=> False PASS of GIC BSA Test- 205

val/common/include/acs_memory.h, val/common/src/AArch64/PeTestSupport.S, val/common/src/acs_exerciser.c, val/common/src/acs_memory.c, val/common/src/acs_pcie.c, val/sbsa/include/sbsa_acs_mpam.h, val/sbsa/src/AArch64/MpamSupport.S, val/sbsa/src/sbsa_acs_mpam.c
- Fixes #422
- Update copyright years to 2025
- Writes to PCIe address can go out of order due to support of weak memory modelling
- Adding DSB SY instruction after every PCIe write to ensure the writes are successful before execution of next instruction
=> Preserve memory ordering for PCIe writes

val/common/src/acs_timer.c
- val_platform_timer_get_entry_index incorrectly iterated through the available timers.
- Change instance > timers_in_block to instance >= timers_in_block.
Change-Id: Ie32de61f7cff1a23bbb6932778165ea6e08f9daf
=> acs_timer: Fix timer indexing access

baremetal_app/BsaAcs.h, baremetal_app/BsaAcsMain.c, linux_app/bsa-acs-app/bsa_app_main.c, linux_app/bsa-acs-app/include/bsa_app.h, pal/baremetal/target/RDN2/common/include/platform_override_fvp.h, pal/baremetal/target/RDN2/common/src/platform_cfg_fvp.c, uefi_app/BsaAcs.h, uefi_app/BsaAcsMain.c, val/bsa/include/bsa_val_interface.h, val/bsa/src/bsa_execute_test.c, val/common/include/acs_cfg.h
- Added new macros for BSA level support (BSA_MIN_LEVEL_SUPPORTED, BSA_MAX_LEVEL_SUPPORTED).
- Introduced new global variables (g_bsa_level, g_bsa_only_level, g_bsa_run_fr, g_bsa_run_only).
- Added command-line options for BSA levels (-l, -only, -fr).
- Modified functions to include conditional checks based on BSA levels.
-Updated print statements to reflect these changes
=> Adding level, fr and only option in BSA

baremetal_app/BsaAcs.inf, test_pool/pe/operating_system/test_os_c015.c, uefi_app/BsaAcs.inf, uefi_app/BsaAcsMem.inf, val/bsa/include/bsa_acs_pe.h, val/bsa/src/bsa_execute_test.c
Changes:
- A new test file has been added for Rule B_PE25.
- This file includes a test for checking FEAT_LSE support by reading and validating the ID_AA64ISAR0_EL1 register.
- The test sets the status to pass if the Atomic feature is supported (values 0b0010 or 0b0011), otherwise it fails.
- A new condition is added to call the os_c015_entry function if g_bsa_level > 1 or g_bsa_only_level == 2.
=> New Test B_PE_25 for FR in BSA

val/sbsa/include/sbsa_acs_mpam.h, val/sbsa/include/sbsa_acs_pe.h, val/sbsa/src/sbsa_execute_test.c
Changes:
- This is part of sbsa errata 483
- The S_MPAM_PE rule is removed from level 5
- The virtual PARTID and cache portion partioning is moved from l5 to l7
- The rule S_L7MP_06. S_L7MP_07 are removed
=> Errata - 483: Clarify the MPAM PARTID

pal/uefi_acpi/sbsa/src/pal_sbsa_mpam.c
- intrf_type is used in place of identifier to correctly get the Interface type
=> Bug fix in PAL mpam Code

pal/baremetal/sbsa/include/pal_sbsa_common_support.h, pal/baremetal/target/RDN2/sbsa/include/platform_override_sbsa_struct.h, pal/uefi_acpi/sbsa/include/pal_sbsa_uefi.h, val/sbsa/include/sbsa_acs_pmu.h, val/sbsa/include/sbsa_acs_pmu_reg.h, val/sbsa/include/sbsa_pal_interface.h, val/sbsa/include/sbsa_val_interface.h, val/sbsa/src/sbsa_acs_pmu.c
- The SBSA PMU test relies on the CoreSight PMU architecture for register memory layout.
- Read the PMDEVARCH register to check the same and skip if PMU node not following CS register layout.
=> PMU changes: Read PMU PMDEVARCH reg to query cs complaint

test_pool/pcie/operating_system/test_os_p064.c
Failure of MSI tests are seen with Linux 6.12, enabling more debug prints.
=> debug prints in 864

pal/baremetal/common/src/pal_pcie_enumeration.c, pal/uefi_acpi/common/src/pal_pcie_enumeration.c, pal/uefi_dt/bsa/src/pal_pcie_enumeration.c, val/common/include/pal_interface.h, val/common/src/acs_pcie.c
- Fixes #418
- Added PAL API to provide support to skip the buses during PCIe table creation to ensure less time taken in pre-silicon
- Change in Copyright of files.
=> Support to limit scanning entire PCIe space

val/common/src/acs_pcie.c, val/common/src/acs_peripherals.c
- Fixes #478 and #479
- Moved the code to skip the PCIe buses before the check of the device and function of that bus.
- Added same logic to Peripheral create info table
=> Limit Scanning entire PCIe space

val/common/src/AArch64/PeRegSysSupport.S
Fixes #482 
- The Limit Address is set by adding 4KB to Base address
- For each PE the trace buffer address limit is 4KB
=> Incorrect TRBLIMITR_EL1.LIMIT Value

val/common/src/AArch64/PeRegSysSupport.S
Fixes #484 
-Instead of making whole register TRBLIMITR_EL1 as zero 
-Only the Enable Field is set to zero to disable Trace
=> TRBLIMITR_EL1.E set to 0 (Disable Trace)

pal/uefi_dt/bsa/src/pal_pe.c
Fix https://github.com/ARM-software/arm-systemready/issues/403
=> Set smbios table slot_count to 0 if protocol not exist

val/sbsa/src/sbsa_acs_ete.c
Fixes #497 
Corrected bit extraction logic for trace info packet
- This commit updates the calls to VAL_EXTRACT_BITS to use the correct single-bit
=> Corrected bit extraction logic for trace info packet
