test_pool/pcie/operating_system/test_os_p011.c
=> PCIe: Using Bus number register to perform checks

test_pool/pcie/operating_system/test_os_p002.c
=> PCIe: RP is not assumed to be on Dev 0 Func 0

test_pool/gic/operating_system/test_os_its003.c
- Dynamically allocate memory for streamID for ITS test 3.
Fix for #17 
Signed-off-by: amr01 <amrathesh@arm.com>
=> Fix for ITS test 3 issue #17

test_pool/power_wakeup/operating_system/test_os_u001.c, val/include/val_interface.h, val/src/acs_wd.c
* Point 1 in issue is already taken care by BSA
* Incorporated fix for point 2
Signed-off-by: jisjos01 <jiss.jose@arm.com>
=> Fix for SBSA issue : https://github.com/ARM-software/sbsa-acs/issues/229

linux_app/bsa-acs-app/bsa_app_main.c
Signed-off-by: Shyamanth RH <shyamanth.rh@arm.com>
=> Removed OS/HYP/PS options from online help

linux_app/bsa-acs-app/bsa_app_main.c, linux_app/bsa-acs-app/include/bsa_app.h, uefi_app/BsaAcs.h, uefi_app/BsaAcsMain.c, val/src/acs_pcie.c, val/sys_arch_src/smmu_v3/smmu_v3.c
- added subminor version prints
- this integrates with SystemReady IR ACS v2.0.0 Beta-0
=> BSA changes for v1.0.1

test_pool/memory_map/operating_system/test_os_m004.c, val/include/pal_interface.h, val/include/val_interface.h, val/src/acs_pcie.c
Moving Addressability of Non-Secure Masters test fix from SBSA to BSA
=> #30 Test updated to check if pcie device driver present

linux_app/bsa-acs-app/bsa_app_main.c, test_pool/pcie/operating_system/test_os_p030.c, test_pool/pcie/operating_system/test_os_p036.c, test_pool/power_wakeup/operating_system/test_os_u001.c, test_pool/timer/operating_system/test_os_t001.c, test_pool/watchdog/operating_system/test_os_w002.c, uefi_app/BsaAcs.h, uefi_app/BsaAcsMain.c, val/include/bsa_acs_pcie.h, val/include/bsa_acs_pcie_spec.h, val/src/acs_exerciser.c, val/src/acs_iovirt.c, val/src/acs_pcie.c, val/src/acs_wd.c, val/sys_arch_src/smmu_v3/smmu_v3.c
Below SBSA issues fixes is moved to BSA
https://github.com/ARM-software/sbsa-acs/issues/232
https://github.com/ARM-software/sbsa-acs/issues/238
https://github.com/ARM-software/sbsa-acs/issues/233
https://github.com/ARM-software/sbsa-acs/issues/242
https://github.com/ARM-software/sbsa-acs/issues/235
=> Moving required fixes from SBSA to BSA ACS

uefi_app/BsaAcs.inf
=> enforce no optimization for test layer build

test_pool/peripherals/operating_system/test_os_d005.c
- Test case 606 UART loopback test doesn't mask off MSR delta bits
https://github.com/ARM-software/bsa-acs/issues/48
- Test case 606 assuming system clock reference for UART
https://github.com/ARM-software/bsa-acs/issues/43
Signed-off-by: Gowtham Siddarth <gowtham.siddarth@arm.com>
Change-Id: I77d0c2576709afc3292d2c7dbe7c6ed75a9f1ae6
=> PJ03206-628: Fixues for clock reference for test 606

test_pool/peripherals/operating_system/test_os_d005.c, uefi_app/BsaAcs.h, uefi_app/BsaAcsMain.c, val/include/bsa_acs_cfg.h, val/include/val_interface.h, val/src/acs_exerciser.c, val/src/acs_gic.c, val/src/acs_memory.c, val/src/acs_pcie.c, val/src/acs_pe.c, val/src/acs_peripherals.c, val/src/acs_smmu.c, val/src/acs_test_infra.c, val/src/acs_timer.c, val/src/acs_wakeup.c, val/src/acs_wd.c
=> Added feature to select individual tests for bsa-acs

tools/scripts/acsbuild.sh
Code changes to allow for aarch64 native build
=> AArch64 native build support

test_pool/gic/hypervisor/test_hyp_g001.c, val/src/acs_smmu.c
* Enable run of gic hyp test 1 for bsa
* Added the interrupt id check for gic hyp ppi test
=> run gic hyp 1 test for bsa

val/src/acs_pcie.c
Signed-off-by: Shyamanth RH <shyamanth.rh@arm.com>
=> Fix to select single pcie test to run

test_pool/gic/operating_system/test_os_its003.c
Issue #80 : test_os_its003.c modified for system with multiple SMMU instances.
Signed-off-by: Rajat Goyal <rajat.goyal@arm.com>
=> ITS : Fix for Issue

val/src/acs_peripherals.c
val : Fix for Peripheral Dump Info 
- Added the check for Start Bus & End Bus number
Signed-off-by: Rajat Goyal <rajat.goyal@arm.com>
=> val : Fix for Peripheral Dump Info

README.md, linux_app/bsa-acs-app/include/bsa_app.h, platform/pal_uefi_acpi/src/pal_pe.c, platform/pal_uefi_dt/src/pal_dt_debug.c, test_pool/memory_map/operating_system/test_os_m002.c, uefi_app/BsaAcs.h, val/include/bsa_acs_exerciser.h, val/src/acs_exerciser.c, val/src/acs_pcie.c
* Exerciser test suite using exerciser info table.
* Memory test 2 gcc warning suppress
Co-authored-by: Amrathesh <amrathesh@arm.com>
Co-authored-by: Shyamanth R H <shyamanth.rh@arm.com>
Co-authored-by: Rajat Goyal <rajat.goyal@arm.com>
Co-authored-by: Balaji Gontumukkala <balaji.gontumukkala@arm.com>
Co-authored-by: Gowtham Siddarth <gowtham.siddarth@arm.com>
Co-authored-by: Sujana M <sujana.m@arm.com>
Co-authored-by: Chetan Rathore <chetan.rathore@arm.com>
Co-authored-by: Srikar Josyula <srikar.josyula@arm.com>
=> BSA 1.0.3 release changes

test_pool/gic/operating_system/test_os_its003.c, test_pool/gic/operating_system/test_os_its004.c, val/src/acs_gic.c, val/src/acs_iovirt.c
For Issue #84 
- Test was returning with failure if check failed for one of the device, Changes done to tests to continue running for all the devices and then report the status.
- Modified the print message.
Signed-off-by: Rajat Goyal <rajat.goyal@arm.com>
=> Changes for Issue #84 : ITS Test 278, 279 Improvement

val/src/acs_gic.c
- changed verbosity of GICv2m skip print to INFO.
- checks added to run test 202 only if GICv2 is present.
- added GIC version print.
Fixes #87 
=> Run test 202 (B_GIC_02) only for system with GICv2

test_pool/gic/operating_system/test_os_its003.c, test_pool/gic/operating_system/test_os_its004.c
Issue #90 : Fix for test 278,279 in case of no SMMU 
- Previously test was checking for Stream ID even if device is not behind SMMU, test case is now changed to Skip the Stream ID related checks for devices which are not behind SMMU with the help of smmu_id.
- Debug message prints are improved.
Signed-off-by: Rajat Goyal <rajat.goyal@arm.com>
=> Issue #90 : Fix for test 278,279 in case of no SMMU

test_pool/smmu/operating_system/test_os_i002.c
- Updated the SMMU test 302 to check for updated bit fields of ID_AA64MMFR0_EL1.TGran4 and ID_AA64MMFR0_EL1.TGran16 values as per Arm Arm I.a.
Signed-off-by: Balaji Gontumukkala <balaji.gontumukkala@arm.com>
=> SMMU test 302 updated for PE supporting FEAT_LPA2

platform/pal_uefi_acpi/src/pal_pe.c
Fix #132 
* Check MADT (GICC CPU interface flags) enabled and online capable bit
* if either of those bits are set, then only add pe
* if both bits are clear, pe is unusable
Pending: Similiar changes for pal_uefi_dt
=> Only add usable PE in pe_info_table

test_pool/pcie/operating_system/test_os_p009.c
- bsa-acs Tests 809 should continue test of all RPs even if an issue is found
- Change Extended Capability IDs upto 34h
=> Ext Cap ID modified and test continuity added

test_pool/gic/operating_system/test_os_its004.c
Issue #131 : Fix for ITS Test 279
- Included a new check for the Segment number for StreamID association check.
- Resolved the issue with the StreamID check for devices. Previously, the test would skip checking the StreamID for future devices as soon as it detected the first device that wasn't located behind SMMU. This has been fixed now
=> Issue #131 : Fix for ITS Test 279

val/src/acs_pcie.c
- Padding done for better readability when higher verbosity is used
- Added BDF info as part of PCIe info
=> Fix for issue #128 and #129

test_pool/pcie/operating_system/test_os_p009.c
- Next Capability Pointer is bits [8:15]
=> Next Capability Pointer Fix

uefi_app/BsaAcs.h
Issue #134 : Increase IORT Table Size
- Increased the IORT Info table size to accomodate 600 typical IORT nodes.
=> Issue #134 : Increase IORT Table Size

test_pool/smmu/operating_system/test_os_i003.c
=> 303 test description updated to reflect it checks SMMU LPA support

val/src/acs_pcie.c
- Whenever the test encounters an EP without an assigned RP, the system will report error. Simultaneously, the test will continue its execution without interruption, progressing with the evaluation of other tests as usual. By implementing this change, we can maintain the overall efficiency of our testing operations while proactively addressing any incomplete or missing information.
- Fix for issue https://github.com/ARM-software/bsa-acs/issues/112
=> ACS continues to test PCIe with Hierarchy error

test_pool/pcie/operating_system/test_os_p008.c
- The end bus number for the test is the least of end bus value in ACPI and bus value in max BDF in the ACS BDF table. The test then checks from "end bus + 1"
- But if devices are skipped, accessing the "end bus + 1" will be a valid entry.
- Added logic to instead obtain the maximum subordinate bus number of the segment from the RP BDF's.
=> Bug fix for PCIe test p008

platform/pal_uefi_acpi/include/pal_uefi.h, platform/pal_uefi_acpi/src/pal_pcie.c, platform/pal_uefi_acpi/src/pal_pcie_enumeration.c, platform/pal_uefi_dt/include/pal_uefi.h, platform/pal_uefi_dt/src/pal_pcie.c, platform/pal_uefi_dt/src/pal_pcie_enumeration.c
- Each HandleBuffer needs a FreePool (HandleBuffer) as mentioned in spec
- Aligns to #158
=> Each HandleBuffer needs FreePool

platform/pal_baremetal/FVP/RDN2/include/platform_override_fvp.h, val/include/pal_interface.h, val/sys_arch_src/smmu_v3/smmu_v3.c
- SID bits can now be modified to avoid memory allocation issues when all SID bits are not required
=> Added support to modify the SID bits

test_pool/exerciser/operating_system/test_os_e014.c, test_pool/smmu/operating_system/test_os_i003.c, val/src/acs_pcie.c, val/sys_arch_src/smmu_v3/smmu_reg.h
- Formatting changes for better ACS readability.
- Copyright updates.
=> Formatting and copyright changes

test_pool/exerciser/operating_system/test_os_e002.c
- When -p2p is enabled, exerciser tests 901 and 902 are run additionally. Running test 902 causes 905 test to fail.
- smmu_unmap was called outside of the function that enabed smmu_map. This was leading to the mappings to not be cleared and leading to consecutive tests depended on smmu to fail.
- Moved smmu_unmap and smmu_map within the same function. This frees the mappings and and page tables created.
=> Fix for exerciser Test 902:

val/src/acs_pcie.c
- Provided additional prints for Tests to output expected and read values of attributes
=> Fix for issue #183

test_pool/pcie/operating_system/test_os_p009.c, test_pool/smmu/hypervisor/test_hyp_i002.c, test_pool/smmu/operating_system/test_os_i004.c
Test Description Formatting Changes
=> Test Description Formatting Changes

test_pool/pe/operating_system/test_os_c012.c
Fixes: #213
- removed the logical greater symbol.
=> Fix PE test 12 bug

test_pool/exerciser/operating_system/test_os_e001.c, test_pool/exerciser/operating_system/test_os_e002.c, test_pool/exerciser/operating_system/test_os_e006.c, test_pool/pcie/operating_system/test_os_p006.c, test_pool/pcie/operating_system/test_os_p018.c
- README mentions that certain API's are platform dependent
- Adding the info as print msg for better understanding to customers
=> Fix for Issue #208

platform/pal_uefi_dt/src/pal_pe.c
In DT v0.4 specification "fail" value of status field is added, to indicate PE is not operational or exist
=> SKIP non-exist/unusable PE from PE info table for Device Tree platforms

test_pool/pe/hypervisor/test_hyp_c004.c
-The test case is updated to check PMUv3 before checking PMU counters
=> Check PMUv3 is added to test_hyp_c004.

test_pool/smmu/hypervisor/test_hyp_i002.c, test_pool/smmu/operating_system/test_os_i004.c
- Tests has been updated to check for S_EL2 Support in PE and SMMUv3.2 Support
=> Issue #237 : SMMU S_EL2 Test Updates

val/src/acs_gic.c
Using GIC Registers to set trigger type
- Previously test was using gHardwareInterrupt2ProtocolGuid to set the trigger type.
=> Fixes #263 : Using GIC Registers to set trigger type

test_pool/pcie/operating_system/test_os_p063.c
- Added additional prints with details on the bdf and the irq pin
=> Fix for Issue #264

.github/workflows/build-bsa.yml, README.md
- Added baremetal compilation check for RDN2 platform as part of GitHub actions.
- Saving Baremetal binary as an artifact on GitHub Actions.
=> Baremetal compilation check for GitHub Actions

.github/workflows/bsa-acs_build_check.yml, .github/workflows/bsa-acs_daily_build.yml, README.md
Split of .yml files based on:
- check-in build
- daily build
=> Enhancement to Github Actions 

pal/baremetal/target/RDN2/common/src/platform_cfg_fvp.c, pal/baremetal/target/RPi4/src/platform_cfg_fvp.c, test_pool/pe/operating_system/test_os_c006.c, uefi_app/BsaAcsMain.c, val/common/include/acs_cfg.h, val/common/include/val_interface.h, val/sbsa/include/sbsa_val_interface.h
Fixes  #270 
-Skip test_os_c006 based on command line argument
-The value of -no_crypto_ext flag depends on export restriction on crypto
=> Check export restriction for crypto extension.

val/sbsa/src/sbsa_execute_test.c
Rearranging TARGET_LINUX flag to resolve end of function reached error
=> SBSA Linux build compilation fix

.github/workflows/bsa-acs_build_check.yml
Compile Linux
Compile BSA ACS Linux module and app
Compile SBSA ACS Linux module and app
=> Adding BSA and SBSA Linux build checks to Daily checker script

uefi_app/BsaAcs.h
- Increase in PCIe table size to accomodate for 40 RC
=> Increase in PCIe table size

pal/baremetal/common/src/pal_peripherals.c, pal/uefi_acpi/common/src/pal_peripherals.c, pal/uefi_dt/bsa/src/pal_peripherals.c, test_pool/pcie/operating_system/test_os_p042.c
- Made changes in test p042 to take max_pasid from VAL API.
=> Fix for issue #286: Obtain max pasid info from val

docs/PCIe_Exerciser/README.md, docs/arm_bsa_testcase_checklist.rst
- arm_bsa_testcase_checklist.rst file to be rendered correctly on Github
- README.md file pointing to the latest stack
=> Change in .rst file and README.md file

test_pool/pe/operating_system/test_os_c001.c
Fixes #307 
* Update the CCSIDR mask for 64 bit value.
* correct the failure debug print for CCSIDR register to print the selected cache value
=> add more debug prints + mask value update

pal/uefi_dt/bsa/src/pal_pe.c
Check Cortex-A76 and Cortex-A55 PMU
=> PAL: Add a55 and a76 pmu dt compatibles

val/common/src/acs_timer.c
Fix for #339 
- Added changes to show timer frequency in MHz
=> Show TIMER_INFO: System Counter frequency in decimal #339

drtm/test_pool/dl/test_dl004.c, drtm/test_pool/dl/test_dl005.c, pal/uefi_dt/bsa/src/pal_iovirt.c, test_pool/exerciser/operating_system/test_os_e007.c, test_pool/exerciser/operating_system/test_os_e008.c, test_pool/power_wakeup/operating_system/test_os_u002.c, test_pool/power_wakeup/operating_system/test_os_u003.c, test_pool/power_wakeup/operating_system/test_os_u004.c, test_pool/power_wakeup/operating_system/test_os_u005.c, val/drtm/include/drtm_acs_defines.h, val/drtm/include/drtm_val_interface.h, val/drtm/src/AArch64/Drtm.S, val/drtm/src/drtm_acs_interface.c
- log formatting
- DRTM enhancements
=> Log formatting and minor DRTM enhancements

val/common/src/acs_gic.c
=> Added missing \n in print

val/sbsa/src/sbsa_execute_test.c
Fixes: ARM-software/sbsa-acs#495
=> Reformat exerciser print

test_pool/pe/operating_system/test_os_c001.c
The print alignment for PE Test 01 is aligned with other test results
=> Test 01 Print Alignment for level 3

.github/workflows/bsa-acs_build_check.yml, .github/workflows/bsa-acs_daily_build.yml
- Changes to take the latest edk2
- Currently taking to stable edk2 commit 836942fbadb629050b866a8052e6af755bcdf623
=> Fixes https://github.com/ARM-software/sbsa-acs/issues/505

test_pool/exerciser/operating_system/test_os_e004.c, test_pool/exerciser/operating_system/test_os_e005.c, test_pool/exerciser/operating_system/test_os_e007.c, test_pool/exerciser/operating_system/test_os_e008.c, test_pool/pcie/operating_system/test_os_p008.c, val/common/include/val_interface.h, val/common/src/acs_gic_support.c, val/common/src/acs_pe_infra.c, val/common/sys_arch_src/gic/its/acs_gic_its.c, val/common/sys_arch_src/gic/its/acs_gic_its.h, val/common/sys_arch_src/gic/its/acs_gic_redistributor.c
Multiple changes being submitted, these are tested at a live project and verified locally in our setup as well.
=> Changes required in ITS, GIC drivers and tests

pal/baremetal/common/include/pal_pcie_enum.h, pal/baremetal/common/src/pal_pcie_enumeration.c, test_pool/pcie/operating_system/test_os_p008.c, val/common/src/acs_pe_infra.c, val/common/sys_arch_src/gic/its/acs_gic_its.c
- Changes to the code for better readability
- Consider segment as well along with the bus, device and function of a PCIe device during enumeration.
=> Code changes for better readability and Enumeration support for multi-segment

README.md, baremetal_app/BsaAcs.h, docs/PCIe_Exerciser/README.md, docs/arm_bsa_testcase_checklist.rst, linux_app/bsa-acs-app/include/bsa_app.h, mem_test/README.md, uefi_app/BsaAcs.h
- Changed the ACS version to 1.0.9
- Changes to READMe file on edk2 commit and release
- change to checklist
=> Changes to READMe and version

test_pool/timer/operating_system/test_os_t001.c
Fixes #399 
- Added changes to display counter frequency in MHz/KHz
=> Added logic to display frequency in decimal

.github/workflows/bsa-acs_build_check.yml, .github/workflows/bsa-acs_daily_build.yml
- Updated the CI files to take ubuntu-22.04 instead of ubuntu-latest as this picks up ubuntu-24.04 randomly
=> Update to .yml files for CI

drtm/test_pool/dl/test_dl001.c, drtm/test_pool/dl/test_dl002.c, drtm/test_pool/dl/test_dl003.c, drtm/test_pool/dl/test_dl004.c, drtm/test_pool/dl/test_dl006.c, drtm/test_pool/dl/test_dl007.c
- Logic to check is the log is zeroed and break the loop which indicates end of log.
- Updated check point numbers.
=> Added logic to check end of event log

val/sbsa/include/sbsa_acs_timer.h, val/sbsa/include/sbsa_val_interface.h, val/sbsa/src/sbsa_execute_test.c
Changes:
-New Test Rule S_L8TI_01 added in sbsa
-Added the function call in sbsa execute API
=> Errata 577: New Rule S_L8TI_01

README.md, baremetal_app/BsaAcs.h, linux_app/bsa-acs-app/include/bsa_app.h, uefi_app/BsaAcs.h
The BSA Version is changed from 1.0.9 to 1.1.0
=> Readme and Version Change

test_pool/timer/operating_system/test_os_t005.c
- Added SKIP logic to skip the test if the CNT Base is 0
- Changes to Copyright
=> Bug fix for Timer Test t005

val/bsa/src/bsa_acs_dma.c, val/common/src/acs_gic.c, val/common/src/acs_iovirt.c, val/common/src/acs_memory.c, val/common/src/acs_mpam.c, val/common/src/acs_pcc.c, val/common/src/acs_pcie.c, val/common/src/acs_pe.c, val/common/src/acs_pe_infra.c, val/common/src/acs_peripherals.c, val/common/src/acs_timer.c, val/common/src/acs_wd.c, val/sbsa/src/sbsa_acs_pmu.c, val/sbsa/src/sbsa_acs_ras.c
Adding null pointer checks while freeing the memory to avoid dangling pointers or crash
=> Added Checks for NULL pointer before freeing info table memory

test_pool/power_wakeup/operating_system/test_os_u004.c, test_pool/watchdog/operating_system/test_os_w002.c
- Ensure that when watchdog tests fail, the system does not reset and the BSA suite can gracefully finish.
- Set failsafe timeouts to be 1.5x WDT period to prevent race conditions between failsafe timeout and WDT.
Change-Id: I3f53fb849404a081eaa963a502c562c408e8395e
=> test_pool: Prevent watchdog tests from reseting system

README.md, pal/uefi_acpi/common/include/pal_uefi.h, test_pool/memory_map/operating_system/test_os_m004.c, test_pool/pcie/operating_system/test_os_p062.c, test_pool/pcie/operating_system/test_os_p064.c, test_pool/peripherals/operating_system/test_os_d004.c, val/bsa/include/bsa_val_interface.h, val/bsa/src/bsa_acs_dma.c, val/common/include/pal_interface.h
-The changes related to Linux porting
-The test related to DMA are updated to work without patch.
- The README for Linux ACS Module Build is added.
=> BSA Changes for Linux Porting
